#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
xss-lock -- ~/.scripts/lockscreen &
nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }" &
xwallpaper --maximize ~/Pictures/Wallpapers/wallpaper.png &
picom --experimental-backends &
nm-applet &
blueman-applet &
greenclip daemon &
dunst &
flameshot &
udiskie &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           6
bspc config top_padding			 34

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off